# Generated by Django 5.0.4 on 2024-06-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_user_image_alter_chat_icon_user_alter_post_icon_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
